FROM node:18 as node_app

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

FROM nginx:alpine

COPY --from=node_app /app /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]